# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-14 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistematurnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='codigo',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='termino',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
