# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-17 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistematurnos', '0003_auto_20200217_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='dias',
            field=models.ManyToManyField(related_name='dias', to='sistematurnos.Dia'),
        ),
    ]
